'use strict';
(() => {
 let token = ''; let working = false; let pendingUpgrade='';
 const $ = s => document.querySelector(s);
 const stages = {environment:'检查 Docker',pull:'下载固定版本镜像（可关闭终端中断）',neo4j:'启动图数据库',migrate:'初始化数据结构',teacher:'创建教师账户',app:'启动网站与任务处理',readiness:'检查全部服务就绪',stopping:'停止服务',stopped:'已停止'};
 const message = text => { $('#message').textContent=text; };
 const clearSecrets = () => document.querySelectorAll('input[type="password"]').forEach(x=>{x.value='';});
 async function api(path, body, seed) {
  const response = await fetch('/control/'+path, {method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(seed||token)},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store'});
  const data = await response.json(); if(!response.ok) throw new Error(data.Message || '本机控制会话已失效，请重新双击启动。'); return data;
 }
 function fields(form){return Object.fromEntries(new FormData(form));}
 async function refresh(){try{const s=await api('status');pendingUpgrade=s.pending_upgrade_id||''; if(!$('#new-port').dataset.loaded&&s.web_port){$('#new-port').value=s.web_port;$('#new-port').dataset.loaded='1';} $('#setup').hidden=s.phase!=='NEW';$('#existing').hidden=s.phase==='NEW';$('#resume-form').hidden=!(s.needs_teacher);$('#account-notice').textContent=s.account_notice||'';$('#status').textContent=(stages[s.stage]||s.phase)+(s.busy?' · 请稍候':'');if(s.failure)message(s.failure.Message);for(const button of document.querySelectorAll('[data-action]')){button.disabled=working||s.busy||!s.actions.includes(button.dataset.action);}$('#install').disabled=working||s.busy;}catch(e){message(e.message);}}
 const KNOWN_DIMENSIONS={'text-embedding-v4':[64,128,256,512,768,1024,1536,2048]};
 function dimensionProblem(model,dimensions){const key=String(model).trim().toLowerCase(),allowed=KNOWN_DIMENSIONS[key];return allowed&&!allowed.includes(dimensions)?key+' 不支持 '+dimensions+' 维。该模型只支持：'+allowed.join('、')+'；推荐 1024。建立索引后维度不能更改，请在列表中选择。':'';}
 const PRESETS={bailian:{base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'text-embedding-v4',dimensions:'1024'}};
 const setupForm=$('#setup-form'),presetSelect=$('#vector-preset');
 const matchesPreset=name=>PRESETS[name]&&Object.entries(PRESETS[name]).every(([k,v])=>setupForm.elements[k].value===v);
 presetSelect.addEventListener('change',()=>{const p=PRESETS[presetSelect.value];if(p){for(const [k,v] of Object.entries(p))setupForm.elements[k].value=v;}else{setupForm.elements.base_url.value='';setupForm.elements.model.value='';setupForm.elements.base_url.focus();}});
 for(const name of ['base_url','model','dimensions'])setupForm.elements[name].addEventListener('input',()=>{if(presetSelect.value!=='custom'&&!matchesPreset(presetSelect.value))presetSelect.value='custom';});
 $('#setup-form').addEventListener('submit',async e=>{e.preventDefault();if(working)return;const f=fields(e.target);const problem=dimensionProblem(f.model,Number(f.dimensions));if(problem){message(problem);setupForm.elements.dimensions.focus();return;}working=true;const payload={embedding:{base_url:f.base_url,model:f.model,dimensions:Number(f.dimensions),api_key:f.api_key},teacher_username:f.teacher_username,teacher_password:f.teacher_password,confirm_password:f.confirm_password,web_port:Number(f.web_port)};try{await api('setup',payload);clearSecrets();message('配置格式检查通过；供应商连接与额度未验证。正在启动本机服务。');}catch(e){message(e.message);}finally{clearSecrets();payload.embedding.api_key='';payload.teacher_password='';payload.confirm_password='';working=false;await refresh();}});
 document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',async()=>{if(working)return;const action=button.dataset.action;if(action==='port'&&!window.confirm('更换端口需要先停止本安装的服务，保留课程与密钥。确认？'))return;if((action==='upgrade'||action==='restore')&&!window.confirm(action==='upgrade'?(pendingUpgrade?'备份已完成，确认升级此安装？':'停止本安装并创建整组备份？下一步再确认升级。'):'恢复只写暂存卷；检查通过后需再次点击确认切换。原卷保留。'))return;if(action==='stop'&&!window.confirm('停止本安装的服务并保留数据？'))return;working=true;try{let body={};if(action==='port')body={web_port:Number($('#new-port').value),confirmed:true};if(action==='upgrade'||action==='restore'){body={confirmed:true};const id=action==='upgrade'?pendingUpgrade:$('#backup-id').value.trim();if(id)body.backup_id=id;}if(action==='start'&&!$('#resume-form').hidden)body=fields($('#resume-form'));const result=await api(action,body);clearSecrets();if(action==='diagnostics'){const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='smartsketch-diagnostic.json';link.click();URL.revokeObjectURL(link.href);}else message('操作已接受。');}catch(e){message(e.message);}finally{working=false;await refresh();}}));
 const seed=location.hash.slice(1);history.replaceState(null,'',location.pathname);api('exchange',{},seed).then(s=>{token=s.token;refresh();setInterval(refresh,3000);}).catch(e=>message(e.message));
})();
